# Chapter 5 - Coding Challenge

The netflix.csv data set is a collection of almost 6,000 titles that were available to watch in November 2019 on the video streaming service Netflix.  
It includes four columns: 
 - the video’s title, 
 - director, 
 - the date Netflix added it, and 
- its type/category. 
    
The directorand date_added columns contain missing values. We can see examples at index positions 0, 2, and 5836 of the following output:

In [5]:
import pandas as pd
df_netflix = pd.read_csv("netflix.csv", parse_dates=['date_added'])

C:\Users\lorra\AppData\Local\Temp\ipykernel_20408\857267912.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_netflix = pd.read_csv("netflix.csv", parse_dates=['date_added'])

In [6]:
df_netflix.head()

               title        director date_added     type
0        Alias Grace             NaN 2017-11-03  TV Show
1     A Patch of Fog  Michael Lennox 2017-04-15    Movie
2           Lunatics             NaN 2019-04-19  TV Show
3          Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4  Shrek the Musical     Jason Moore 2013-12-29    Movie

In [7]:
df_netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 182.5+ KB

In [8]:
df_netflix['type'].value_counts()

type
Movie      3939
TV Show    1898
Name: count, dtype: int64

## 1. Optimize the data set for limited memory use and maximum utility.

In [9]:
df_netflix['type'] = df_netflix['type'].astype("category")

In [10]:
df_netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 142.8+ KB

In [11]:
df_netflix['director'].value_counts()

director
Raúl Campos          18
Marcus Raboy         14
Jay Karas            14
Jay Chapman          12
Steven Spielberg      8
                     ..
Peter Ho              1
Andrew Sandler        1
Sofia Coppola         1
Sam Wrench            1
Michael Bonfiglio     1
Name: count, Length: 3024, dtype: int64

## 2. Find all rows with a title of "Limitless".

In [13]:
df_netflix[df_netflix['title'] == 'Limitless']

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless              NaN 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

## 3. Find all rows with a director of "Robert Rodriguez" and a type of "Movie".

In [15]:
director_robert = df_netflix["director"] == "Robert Rodriguez"
movie_type = df_netflix["type"] == "Movie"
df_netflix[director_robert & movie_type]

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,2019-02-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,2019-04-01,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,2019-03-08,Movie
2890,Sin City,Robert Rodriguez,2019-10-01,Movie
3836,Shorts,Robert Rodriguez,2019-07-01,Movie
3883,Spy Kids,Robert Rodriguez,2019-04-01,Movie

## 4. Find all rows with either a date_added of "2019-07-31" or a director of "Robert Altman".

In [18]:
date_2019_07_31 = df_netflix["date_added"] == "2019-07-31"
director_altman = df_netflix["director"] == "Robert Altman"
df_netflix[date_2019_07_31 | director_altman]

                                title       director date_added     type
611                            Popeye  Robert Altman 2019-11-24    Movie
1028        The Red Sea Diving Resort    Gideon Raff 2019-07-31    Movie
1092                     Gosford Park  Robert Altman 2019-11-01    Movie
3473  Bangkok Love Stories: Innocence            NaN 2019-07-31  TV Show
5117                       Ramen Shop      Eric Khoo 2019-07-31    Movie

## 5. Find all rows with a director of "Orson Welles", "Aditya Kripalani", or "Sam Raimi"

In [20]:
great_directors = ["Orson Welles", "Aditya Kripalani", "Sam Raimi"]
df_netflix[df_netflix["director"].isin(great_directors)]

                           title          director date_added   type
946                 The Stranger      Orson Welles 2018-07-19  Movie
1870                    The Gift         Sam Raimi 2019-11-20  Movie
3706                Spider-Man 3         Sam Raimi 2019-11-01  Movie
4243        Tikli and Laxmi Bomb  Aditya Kripalani 2018-08-01  Movie
4475  The Other Side of the Wind      Orson Welles 2018-11-02  Movie
5115    Tottaa Pataaka Item Maal  Aditya Kripalani 2019-06-25  Movie

## 6. Find all rows with a date_added value between May 1, 2019 and June 1, 2019

In [22]:
df_netflix[df_netflix["date_added"].between(left="2019-05-01", right="2019-06-01")]

,title,director,date_added,type
29,Chopsticks,Sachin Yardi,2019-05-31,Movie
60,Away From Home,NaN,2019-05-08,TV Show
82,III Smoking Barrels,Sanjib Dey,2019-06-01,Movie
108,Jailbirds,NaN,2019-05-10,TV Show
124,Pegasus,Han Han,2019-05-31,Movie
...,...,...,...,...
5671,Satan & Adam,V. Scott Balcerek,2019-06-01,Movie
5675,Rim of the World,McG,2019-05-24,Movie
5677,Malibu Rescue,Savage Steve Holland,2019-05-13,Movie
5739,Mission Istaanbul: Darr Ke Aagey Jeet Hai,Apoorva Lakhia,2019-05-16,Movie
5829,The Kindness Diaries,NaN,2019-05-01,TV Show

## 7. Drop all rows with a NaN value in the director column.

In [24]:
df_netflix.dropna(subset=["director"])

                                   title        director date_added   type
1                         A Patch of Fog  Michael Lennox 2017-04-15  Movie
3                              Uriyadi 2     Vijay Kumar 2019-08-02  Movie
4                      Shrek the Musical     Jason Moore 2013-12-29  Movie
5                       Schubert In Love     Lars Büchel 2018-03-01  Movie
6     We Have Always Lived in the Castle   Stacie Passon 2019-09-14  Movie
...                                  ...             ...        ...    ...
5830                         Bibi & Tina     Detlev Buck 2017-04-15  Movie
5832                         The Pursuit     John Papola 2019-08-07  Movie
5833                    Hurricane Bianca   Matt Kugelman 2017-01-01  Movie
5834                        Amar's Hands  Khaled Youssef 2019-04-26  Movie
5835               Bill Nye: Science Guy  Jason Sussberg 2018-04-25  Movie

[3936 rows x 4 columns]

## 8. Identify the days when Netflix added only one movie to its catalog

In [27]:
~(df_netflix["date_added"].duplicated())

0        True
1        True
2        True
3        True
4        True
        ...
5832    False
5833    False
5834    False
5835    False
5836    False
Name: date_added, Length: 5837, dtype: bool

In [33]:
df_netflix.drop_duplicates(subset=["date_added"], keep=False)

,title,director,date_added,type
4,Shrek the Musical,Jason Moore,2013-12-29,Movie
12,Without Gorky,Cosima Spender,2017-05-31,Movie
30,Anjelah Johnson: Not Fancy,Jay Karas,2015-10-02,Movie
38,One Last Thing,Tim Rouhana,2019-08-25,Movie
70,Marvel's Iron Man & Hulk: Heroes United,Leo Riley,2014-02-16,Movie
...,...,...,...,...
5748,Menorca,John Barnard,2017-08-27,Movie
5749,Green Room,Jeremy Saulnier,2018-11-12,Movie
5788,Chris Brown: Welcome to My Life,Andrew Sandler,2017-10-07,Movie
5789,A Very Murray Christmas,Sofia Coppola,2015-12-04,Movie
5812,Little Singham in London,Prakash Satam,2019-04-22,Movie

In [34]:
# check a date
df_netflix[df_netflix["date_added"] == "2013-12-29"]

               title     director date_added   type
4  Shrek the Musical  Jason Moore 2013-12-29  Movie