# Reshaping Data

In this notebook we play around with various reshaping methods available for Series and DataFrames:

- **pivot()** and **pivot_table()**: Group unique values within one or more discrete categories.
- **stack()** and **unstack()**: Pivot a column or row level to the opposite axis respectively.
- **melt()** and **wide_to_long()**: Unpivot a wide DataFrame to a long format.
- **get_dummies()** and **from_dummies()**: Conversions with indicator variables.
- **explode()**: Convert a column of list-like values to individual rows.
- **crosstab()**: Calculate a cross-tabulation of multiple 1 dimensional factor arrays.
- **cut()**: Transform continuous variables to discrete, categorical values
- **factorize()**: Encode 1 dimensional variables into integer labels.

## pivot()

Parameters
The pivot() function typically takes three main arguments: 

- index: The column (or columns) whose unique values will form the new DataFrame''s index (row labels).
- columns: The column (or columns) whose unique values will become the new DataFrame''s column headers.
- values: The column (or columns) to use for populating the new DataFrame''s cell values. If not specified, all remaining columns will be used.

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = {
    "value": range(12),
    "variable": ["A"] * 3 + ["B"] * 3 + ["C"] * 3 + ["D"] * 3,
    "date": pd.to_datetime(["2020-01-03", "2020-01-04", "2020-01-05"] * 4)
}
df = pd.DataFrame(data)
df

    value variable       date
0       0        A 2020-01-03
1       1        A 2020-01-04
2       2        A 2020-01-05
3       3        B 2020-01-03
4       4        B 2020-01-04
5       5        B 2020-01-05
6       6        C 2020-01-03
7       7        C 2020-01-04
8       8        C 2020-01-05
9       9        D 2020-01-03
10     10        D 2020-01-04
11     11        D 2020-01-05

The above dataframe is clearly in LONG format. You can imagine it as some type of time series collection of four variables: A, B, C and D.

To perform time series operations with each unique variable, a better representation would be where the columns are the unique variables and an index of dates identifies individual observations. To reshape the data into this form, we use the DataFrame.pivot() method (also implemented as a top level function pivot()):

In [5]:
pivoted = df.pivot(index="date", columns="variable", values="value")
pivoted

variable    A  B  C   D
date
2020-01-03  0  3  6   9
2020-01-04  1  4  7  10
2020-01-05  2  5  8  11