## 4.11 Coding challenge

In [1]:
import numpy as np
import pandas as pd

### 4.11.1 Problems

The nfl.csv file contains a list of players in the National Football League with similar
Name, Team, Position, Birthday, and Salary columns. See whether you can answer
these questions:

1. How can we import the nfl.csv file? What’s an effective way to convert the values in its Birthday column to datetimes?
2  What are the two ways we can set the DataFrame index to store the player names?
3. How can we count the number of players per team in this data set?
4. Who are the five highest-paid players?
5. How can we sort the data set first by teams in alphabetical order and then by salary in descending order?
6. Who is the oldest player on the New York Jets roster, and what is his birthday?

In [2]:
nfl = pd.read_csv("nfl.csv")

In [3]:
nfl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1655 entries, 0 to 1654
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      1655 non-null   object
 1   Team      1655 non-null   object
 2   Position  1655 non-null   object
 3   Birthday  1655 non-null   object
 4   Salary    1655 non-null   int64
dtypes: int64(1), object(4)
memory usage: 64.8+ KB

In [4]:
nfl.head()

             Name                  Team Position   Birthday   Salary
0    Tremon Smith   Philadelphia Eagles       RB  7/20/1996   570000
1  Shawn Williams    Cincinnati Bengals       SS  5/13/1991  3500000
2     Adam Butler  New England Patriots       DT  4/12/1994   645000
3     Derek Wolfe        Denver Broncos       DE  2/24/1990  8000000
4       Jake Ryan  Jacksonville Jaguars      OLB  2/27/1992  1000000

In [10]:
 # 
nfl = pd.read_csv("nfl.csv", parse_dates = ["Birthday"])

In [11]:
nfl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1655 entries, 0 to 1654
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      1655 non-null   object
 1   Team      1655 non-null   object
 2   Position  1655 non-null   object
 3   Birthday  1655 non-null   datetime64[ns]
 4   Salary    1655 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 64.8+ KB

In [12]:
nfl.head()

             Name                  Team Position   Birthday   Salary
0    Tremon Smith   Philadelphia Eagles       RB 1996-07-20   570000
1  Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
2     Adam Butler  New England Patriots       DT 1994-04-12   645000
3     Derek Wolfe        Denver Broncos       DE 1990-02-24  8000000
4       Jake Ryan  Jacksonville Jaguars      OLB 1992-02-27  1000000

In [13]:
nfl = nfl.set_index(keys="Name")

In [14]:
nfl.head()

                                Team Position   Birthday   Salary
Name
Tremon Smith     Philadelphia Eagles       RB 1996-07-20   570000
Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
Adam Butler     New England Patriots       DT 1994-04-12   645000
Derek Wolfe           Denver Broncos       DE 1990-02-24  8000000
Jake Ryan       Jacksonville Jaguars      OLB 1992-02-27  1000000

In [19]:
# number of players per team
nfl['Team'].value_counts()

Team
New York Jets           58
Washington Redskins     56
Kansas City Chiefs      56
New Orleans Saints      55
San Francisco 49Ers     55
Denver Broncos          54
Minnesota Vikings       54
Los Angeles Chargers    54
Atlanta Falcons         53
Dallas Cowboys          53
Seattle Seahawks        53
Detroit Lions           53
Buffalo Bills           53
Chicago Bears           53
Philadelphia Eagles     52
New York Giants         52
Los Angeles Rams        52
Houston Texans          52
Arizona Cardinals       51
Oakland Raiders         51
Cincinnati Bengals      51
Green Bay Packers       51
Jacksonville Jaguars    50
New England Patriots    49
Indianapolis Colts      49
Carolina Panthers       49
Cleveland Browns        49
Miami Dolphins          49
Baltimore Ravens        48
Tampa Bay Buccaneers    47
Pittsburgh Steelers     47
Tennessee Titans        46
Name: count, dtype: int64

In [18]:
nfl.shape

(1655, 4)

In [21]:
# 3. Who are the five highest-paid players?
nfl.nlargest(n = 5, columns=["Salary"])

                                 Team Position   Birthday    Salary
Name
Kirk Cousins        Minnesota Vikings       QB 1988-08-19  27500000
Marcus Mariota       Tennessee Titans       QB 1993-10-30  20922000
Jameis Winston   Tampa Bay Buccaneers       QB 1994-01-06  20922000
Derek Carr            Oakland Raiders       QB 1991-03-28  19900000
Jimmy Garoppolo   San Francisco 49Ers       QB 1991-11-02  17200000

In [24]:
# 4. How can we sort the data set first by teams in alphabetical order and then by salary in descending order?
nfl.sort_values(by=["Team", "Salary"], ascending=[True, False])

                                   Team Position   Birthday    Salary
Name
Chandler Jones        Arizona Cardinals      OLB 1990-02-27  16500000
Patrick Peterson      Arizona Cardinals       CB 1990-07-11  11000000
Larry Fitzgerald      Arizona Cardinals       WR 1983-08-31  11000000
David Johnson         Arizona Cardinals       RB 1991-12-16   5700000
Justin Pugh           Arizona Cardinals        G 1990-08-15   5000000
...                                 ...      ...        ...       ...
Ross Pierschbacher  Washington Redskins        C 1995-05-05    495000
Kelvin Harmon       Washington Redskins       WR 1996-12-15    495000
Wes Martin          Washington Redskins        G 1996-05-09    495000
Jimmy Moreland      Washington Redskins       CB 1995-08-26    495000
Jeremy Reaves       Washington Redskins       SS 1996-08-29    495000

[1655 rows x 4 columns]

In [30]:
# 5. Who is the oldest player on the New York Jets roster, and what is his birthday?
nfl[nfl["Team"] == "New York Jets"].sort_values(by=["Birthday"]).iloc[0]

Team              New York Jets
Position                      C
Birthday    1985-03-29 00:00:00
Salary                  2400000
Name: Ryan Kalil, dtype: object