# Article
## How to validate you data with statistical tests in python

[Article](https://www.howtogeek.com/how-to-validate-your-data-with-statistical-tests-in-python/)

In [1]:
import numpy as np
import pingouin as pg
import pandas as pd
import seaborn as sns
%matplotlib inline

#### Create a random number generator.

In [2]:
rng = np.random.default_rng()

In [3]:
a = rng.standard_normal(15)

In [4]:
a

array([ 0.65529267, -0.07254372,  0.32860865,  1.09160048,  0.27166892,
        0.66608685,  0.22923809, -0.87875637,  0.19002248, -0.11836366,
        0.38230265, -0.32568996, -0.86596457,  1.67963369,  0.85597023])

#### Check that the data is normally distributed.

In [5]:
pg.normality(a)

          W      pval  normal
0  0.972081  0.887592    True

In [6]:
a.mean()

np.float64(0.2726070965232832)

#### Check against the null hypothesis that the mean of the array is .45

In [7]:
pg.ttest(a, .45)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-1.003076,14,two-sided,0.332847,"[-0.11, 0.65]",0.258993,0.404,0.154705

#### Experimentation with different values to see what happens.