In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1. Selecting two or more columns

In [3]:
# selecing the gender + math score columns
df_exams[['gender', 'math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [7]:
# check out the data type of the selection
type(df_exams[['gender', 'math score']])

pandas.core.frame.DataFrame

In [9]:
# select 2 or more columns using [[]]
df_exams[['gender', 'math score', 'reading score', 'writing score']]

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [6]:
# we can't select 2 or more columns with the "."

# 1. Adding a new column

In [14]:
from scipy.stats import beta
import numpy as np

In [15]:
a, b = 5, 3 # Right-skewed, 
size = len(df_exams)

In [16]:
# Generate values from beta distribution scaled to 0-100
np.random.seed(42)
raw_scores = beta.rvs(a, b, size=size) * 100

In [17]:
# Shift scores so median is ~70
median_shift = 70 - np.median(raw_scores)
adjusted_scores = raw_scores + median_shift

In [18]:
# clip scores to stay within 0-100
adjusted_scores = np.clip(adjusted_scores, 0, 100)
df_exams['language score'] = adjusted_scores

In [19]:
df_exams.describe()

       math score  reading score  writing score  language score
count  1000.00000    1000.000000    1000.000000     1000.000000
mean     66.08900      69.169000      68.054000       69.142943
std      15.16308      14.600192      15.195657       15.356345
min       0.00000      17.000000      10.000000       18.084425
25%      57.00000      59.000000      57.750000       59.615748
50%      66.00000      70.000000      69.000000       70.000000
75%      77.00000      79.000000      79.000000       80.839991
max     100.00000     100.000000     100.000000      100.000000

## 1.2 Adding a new column with an array

The dataframe has 1000 rows so we need an array with 1000 elements

In [21]:
# import numpy (already done)
# create an array of 1000 elements
language_score = np.arange(0,1000)

In [22]:
len(language_score)

1000

In [23]:
# create random integer numbers between 1 and 100
np.random.randint(1, 100, size=1000)

array([60, 88, 73, 95, 15,  4, 63, 40,  9,  9, 26,  4, 81, 16, 15, 99, 52,
       69,  5, 20, 79, 18,  2, 93, 13,  4, 42, 74, 61, 95,  8, 67, 63,  9,
       94, 11, 99, 42, 13, 36, 13, 12, 37, 74, 73, 52, 71,  2, 56, 60, 23,
       40, 64, 85, 23, 29, 78, 90, 51, 69, 95, 89, 31, 50, 20, 55, 81,  2,
       25, 13, 92, 70, 67, 58, 99, 82, 75, 84, 64, 69, 83, 86, 59, 60, 83,
       62, 16, 88, 68, 15, 89, 55, 35, 55, 14, 49, 83,  7, 30, 83, 49, 89,
       16, 51, 72, 82, 92, 80, 83, 42, 17, 63, 45, 77,  7, 27, 10, 34, 36,
       25,  6, 24, 18, 87,  6, 29, 25, 55, 81, 46, 24, 75, 26, 98, 28,  3,
       75, 38, 61, 78, 51, 90, 48, 21, 54, 56, 94, 59, 72, 51, 20, 96, 86,
       59, 71,  9,  1, 29, 63, 72, 56, 68, 35,  3,  7, 27,  1, 91, 80, 71,
       44, 87, 41, 75, 42, 33, 50, 63, 37, 59, 81, 99, 48,  5, 48, 96,  3,
       47, 62, 99, 14, 63, 61, 31, 95, 17, 24, 23, 82, 50, 78, 79, 79, 70,
       27, 15, 50, 36,  8, 79,  3, 62, 47, 77, 98, 88, 96, 61, 32, 94, 13,
        1, 34, 62, 79, 78, 93, 98, 82, 71, 93, 31, 64, 25, 38, 14,  8, 91,
       54,  2, 81, 78, 89, 56, 94, 93, 84, 85, 61, 22, 35, 16, 50, 43, 17,
       80, 58,  2,  4, 85, 39, 98, 94,  6, 81, 89, 69, 69, 20, 64, 16, 51,
       37, 73, 69, 42, 57, 66,  9, 86, 64, 86, 22, 34, 55, 29, 38, 97, 18,
       71, 65, 97,  1, 88,  4,  4, 82, 27, 43, 59, 32, 33, 28, 55, 60, 70,
       62, 80, 34, 87, 88, 56, 13, 56, 18, 54, 77, 43, 39, 61, 42, 81, 79,
       18, 23, 54, 30, 98, 58, 68, 67, 71, 18,  7, 40, 70, 86, 65, 68, 49,
       52, 29, 21, 90, 78,  9, 47, 76, 42, 51, 56, 51, 70, 20, 88, 27, 38,
       72, 65, 54, 24, 47, 71, 83, 86, 63, 57, 55, 60, 99, 62, 30, 93, 22,
       75, 84, 29, 41, 42, 98, 65, 31, 30, 18, 17, 38, 14, 87, 89, 79, 56,
       22, 67, 56, 19, 57, 44, 98, 35,  1, 52, 85, 93, 70, 37, 65, 51,  1,
       91, 21, 53, 16, 61, 54, 40, 26, 80, 92, 65, 74, 64, 43, 17, 59, 23,
        7, 44, 53, 71, 79, 34, 46, 68, 78, 78, 16, 71, 96, 19,  2, 10, 50,
       81, 12, 70, 22, 32, 84,  1, 54, 58, 70, 83, 18,  6, 45, 97, 23, 23,
       26, 77,  7, 79, 44, 27, 26, 97, 79, 36, 55, 64, 91, 57, 69, 61,  2,
       55, 97, 80, 87, 38, 80, 78, 29, 26, 35, 79, 67, 87, 29, 34, 97, 41,
       41, 23, 71,  3, 58, 32, 31, 82, 43,  7,  1, 61, 14, 52, 96,  6, 10,
       71, 90, 98, 30, 21, 60, 81, 97, 74, 63, 42, 51, 64, 76, 56, 80, 41,
       32, 15, 62, 27, 28, 81, 64, 59, 58,  2, 36, 71, 13, 15, 89, 87, 60,
       22, 63, 90, 97, 75, 74, 25, 48, 43, 38, 41, 45, 88, 40, 97, 17, 88,
       57,  2, 96, 62, 88,  9, 68, 81, 17, 50, 94, 40, 58, 75, 85, 21, 18,
       55, 29, 24, 74, 17, 18, 42, 84, 45, 82, 17, 73, 14, 49, 29, 95,  4,
       82, 20, 47,  9, 77, 79, 27, 15, 92, 19, 90, 52, 26, 89, 26, 26, 46,
       92, 49, 82, 96, 53,  3, 66, 97, 42, 19, 17, 33, 76, 49, 56, 63,  3,
       49, 55, 26, 99, 72, 52,  7, 46, 46, 16, 24, 61, 54, 62,  1, 49, 25,
       10, 80, 16, 58, 72, 29, 92,  6, 16, 20, 80, 71, 78, 43, 26, 90, 78,
       71, 33, 26, 45, 84, 63, 67, 52, 68, 26, 75,  2, 14, 30, 49, 12, 90,
       44, 33, 13, 78, 88, 98, 26, 21, 28, 48, 40, 66, 73, 87, 79, 77, 23,
       81, 48,  2, 84, 20, 59, 46,  3, 55, 12, 40, 66, 78, 16, 83, 34, 44,
        6, 77, 64, 22, 18, 12, 52, 94, 51, 71, 96, 48, 19,  6, 84, 27, 53,
       48,  7, 59, 69, 11, 15, 64,  3, 69, 23, 53, 37,  9, 15,  3, 93, 70,
       17, 26, 21, 72, 21, 11, 38, 72, 88, 35, 14, 14, 10, 12, 38, 34, 41,
       10, 17, 17, 67, 62, 95,  1, 12,  4, 42, 13, 98, 85, 86,  4, 82, 69,
       19,  2, 12, 81, 74, 98,  6,  8, 51, 11, 63, 57, 12, 73,  2,  8, 11,
       53, 10, 85, 84,  8, 36, 93, 76, 14, 54, 85, 86, 21, 50, 94, 39, 20,
       88, 87,  7,  9,  1, 26, 38, 38, 61, 44, 86, 44, 74, 62,  6, 17, 51,
       38, 24, 51, 10, 72, 21, 70, 85, 57, 39, 88, 33, 59, 18, 56, 92, 57,
       96, 76, 48, 42, 27, 74, 52, 42, 32, 26, 25, 75, 23, 98, 57, 52, 87,
       93, 31, 64, 71, 33, 85,  2, 18, 47, 33, 98, 84, 35, 51, 18, 88, 72,
       30, 44, 53, 10, 87, 52, 49, 11, 66, 58, 90, 36, 33, 47, 13, 40, 89,
       68, 42, 19, 82, 94, 19, 58, 23, 54, 80, 65, 12, 24, 34, 53,  8, 18,
       57,  5, 26, 30, 54, 13, 83, 29,  3, 90, 58, 76,  2, 75, 28, 82, 77,
       86, 76,  2,  7, 26, 90, 88, 76, 16, 23, 40, 60, 73, 32, 15, 13,  5,
       75, 74, 52, 77, 41, 53, 50, 15,  7, 40, 28, 32, 99, 15, 85, 70, 65,
        4, 11, 26, 61, 37, 23, 93, 85, 91, 40, 77, 23, 16, 94, 61, 68, 80,
       31, 53, 25, 44, 12, 90, 97, 92,  9, 12, 69, 54, 54, 28],
      dtype=int32)

In [24]:
int_language_score = np.random.randint(1, 100, size=1000)

In [25]:
min(int_language_score)

np.int32(1)

In [26]:
max(int_language_score)

np.int32(99)

In [27]:
df_exams['language score'] = int_language_score

In [28]:
df_exams.describe()

       math score  reading score  writing score  language score
count  1000.00000    1000.000000    1000.000000     1000.000000
mean     66.08900      69.169000      68.054000       51.378000
std      15.16308      14.600192      15.195657       28.229949
min       0.00000      17.000000      10.000000        1.000000
25%      57.00000      59.000000      57.750000       28.000000
50%      66.00000      70.000000      69.000000       52.000000
75%      77.00000      79.000000      79.000000       76.000000
max     100.00000     100.000000     100.000000       99.000000

# 1. Adding a new column

## 1.1 assign()

When to use assign?

- Add multiple columns in a single line of code
- When you need to overwrite the values of an existing columns (best practice)

It returns a new object (copy) with all the original columns in addition to the new ones

In [30]:
# create random numbers for our new columns
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [31]:
# create a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [32]:
df_exams.assign(score1=series1, score2=series2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,56,48,67
1,female,group C,some college,standard,completed,69,90,88,99,43,43
2,female,group B,master's degree,standard,none,90,95,93,69,39,79
3,male,group A,associate's degree,free/reduced,none,47,57,44,98,49,85
4,male,group C,some college,standard,none,76,78,75,98,12,52
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,2,10,14
996,male,group C,high school,free/reduced,none,62,55,55,96,39,24
997,female,group C,high school,free/reduced,completed,59,71,65,82,28,44
998,female,group D,some college,standard,completed,68,78,77,77,30,56
999,female,group D,some college,free/reduced,none,77,86,86,69,37,90

## 1.2 insert()

Inserts a new column at a specific position or index

In [35]:
# using insert() to add a column at a specific position
df_exams.insert(1, 'test', series1)

In [36]:
# show dataframe
df_exams.head()

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,48,group B,bachelor's degree,standard,none,72,72,74,56
1,female,43,group C,some college,standard,completed,69,90,88,99
2,female,39,group B,master's degree,standard,none,90,95,93,69
3,male,49,group A,associate's degree,free/reduced,none,47,57,44,98
4,male,12,group C,some college,standard,none,76,78,75,98