In [1]:
import pandas as pd

# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1 Math Operations

## 1.1 Operations in columns

In [4]:
# select a column and calculate total sum
df_exams['math score'].sum()

np.int64(66089)

In [3]:
# count, mean, std, max, and min

In [5]:
df_exams['math score'].count()

np.int64(1000)

In [6]:
df_exams['math score'].sum() / df_exams['math score'].count()

np.float64(66.089)

In [7]:
df_exams['math score'].mean()

np.float64(66.089)

## 1.2 Operation in rows

In [11]:
# calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [12]:
# calculating the average score and assigning the result to a new column
df_exams['average score'] = df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'] / 3

In [16]:
# showing the dataframe
df_exams = df_exams.round(2)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
0,female,group B,bachelor's degree,standard,none,72,72,74,168.67
1,female,group C,some college,standard,completed,69,90,88,188.33
2,female,group B,master's degree,standard,none,90,95,93,216.00
3,male,group A,associate's degree,free/reduced,none,47,57,44,118.67
4,male,group C,some college,standard,none,76,78,75,179.00
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,218.67
996,male,group C,high school,free/reduced,none,62,55,55,135.33
997,female,group C,high school,free/reduced,completed,59,71,65,151.67
998,female,group D,some college,standard,completed,68,78,77,171.67
999,female,group D,some college,free/reduced,none,77,86,86,191.67

# 1 Value Counts

In [17]:
len(df_exams['gender'])

1000

In [18]:
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [19]:
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [20]:
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [22]:
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

# Sort a Dataframe

In [23]:
# sort by a column
df_exams.sort_values(by='math score')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
59,female,group C,some high school,free/reduced,none,0,17,10,20.33
980,female,group B,high school,free/reduced,none,8,24,23,39.67
17,female,group B,some high school,free/reduced,none,18,32,28,59.33
787,female,group B,some college,standard,none,19,38,32,67.67
145,female,group C,some college,free/reduced,none,22,39,33,72.00
...,...,...,...,...,...,...,...,...,...
623,male,group A,some college,standard,completed,100,96,86,224.67
625,male,group D,some college,standard,completed,100,97,99,230.00
962,female,group E,associate's degree,standard,none,100,100,100,233.33
458,female,group E,bachelor's degree,standard,none,100,100,100,233.33
916,male,group E,bachelor's degree,standard,completed,100,100,100,233.33

In [24]:
# sort descending by one column
df_exams.sort_values(by='math score', ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
451,female,group E,some college,standard,none,100,92,97,224.33
458,female,group E,bachelor's degree,standard,none,100,100,100,233.33
962,female,group E,associate's degree,standard,none,100,100,100,233.33
149,male,group E,associate's degree,free/reduced,completed,100,100,93,231.00
623,male,group A,some college,standard,completed,100,96,86,224.67
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,72.00
787,female,group B,some college,standard,none,19,38,32,67.67
17,female,group B,some high school,free/reduced,none,18,32,28,59.33
980,female,group B,high school,free/reduced,none,8,24,23,39.67
59,female,group C,some high school,free/reduced,none,0,17,10,20.33

In [25]:
# sort descending by muliple columns
df_exams.sort_values(by=['math score', 'reading score'], ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
149,male,group E,associate's degree,free/reduced,completed,100,100,93,231.00
458,female,group E,bachelor's degree,standard,none,100,100,100,233.33
916,male,group E,bachelor's degree,standard,completed,100,100,100,233.33
962,female,group E,associate's degree,standard,none,100,100,100,233.33
625,male,group D,some college,standard,completed,100,97,99,230.00
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,72.00
787,female,group B,some college,standard,none,19,38,32,67.67
17,female,group B,some high school,free/reduced,none,18,32,28,59.33
980,female,group B,high school,free/reduced,none,8,24,23,39.67
59,female,group C,some high school,free/reduced,none,0,17,10,20.33

In [26]:
# sort descending with a key function
df_exams.sort_values('race/ethnicity', ascending=True, key=lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
778,female,group A,some college,standard,completed,72,79,82,178.33
546,female,group A,some high school,standard,completed,92,100,97,224.33
820,female,group A,some high school,standard,completed,85,90,92,205.67
741,female,group A,associate's degree,free/reduced,none,37,57,56,112.67
305,male,group A,some college,standard,none,69,67,69,159.00
...,...,...,...,...,...,...,...,...,...
297,male,group E,associate's degree,standard,completed,71,74,68,167.67
293,female,group E,bachelor's degree,standard,none,65,73,75,163.00
289,male,group E,some high school,standard,completed,77,76,77,178.67
206,male,group E,bachelor's degree,standard,none,82,62,62,164.67
499,male,group E,some college,standard,none,76,71,72,171.00

# 1 Create Index

In [31]:
import numpy as np
import random

In [33]:
# creating non repetitive values for the index
new_index = np.arange(0, 1000)

In [35]:
# shuffling the indexes
random.shuffle(new_index)
new_index

array([557, 882, 555, 558, 336, 814, 749, 330, 637, 321, 712, 387, 797,
       865, 967,  68, 135,   1, 139, 526, 869, 612, 705, 805, 881, 877,
       206, 342, 817, 648, 355, 539, 936, 143, 201, 169, 475, 591, 630,
       707, 190, 629, 728,  13, 690, 790, 531, 738, 745, 959, 345, 584,
       578, 691, 662, 788,  97, 739,  76, 663, 394, 465, 151, 215, 493,
       855, 203, 659, 592, 982,  88, 271, 700, 461, 145, 772, 404,  46,
       932, 596, 655, 915, 521, 715, 796, 654, 896,  14, 236, 496, 994,
       514, 646, 153, 547, 878, 968, 583, 403, 607, 566, 305, 536, 205,
       669, 822, 382, 560, 207, 868, 683, 781, 437, 348, 367, 983, 195,
       229, 328, 892, 464, 684, 415,  63, 449, 939, 378,  35, 929, 452,
       128, 589, 523,  39, 816, 357, 802,  69, 676, 253, 147, 358, 903,
       499, 785, 448, 483, 149, 399, 299, 731, 286, 414, 549, 992, 765,
       484, 727, 840, 381, 778, 189, 259, 186, 732, 907, 989, 425, 899,
       541,   5, 505, 800, 832,  93, 421,  86, 763, 289,  58, 450, 335,
       119, 516, 474, 561, 843, 235, 157, 213, 515, 677, 244,  42, 806,
       101, 660, 375, 159, 200, 446, 848,   7, 981, 946, 333, 550, 131,
        66, 125,  22, 666, 485, 635, 686, 611, 489, 758, 430, 542, 454,
       713, 121, 792, 117, 844, 735, 451, 597, 250, 408, 679, 854, 586,
       948, 209, 859,  77, 593, 887, 809, 661, 979, 574, 140, 255, 847,
       307, 833, 278, 927, 396, 789, 234, 426, 761, 947, 436, 836, 471,
       291, 876, 177, 703, 996, 748, 327, 962, 668, 389, 366, 204, 737,
       479, 934, 900, 138, 398,  11, 689, 897, 509, 111, 490, 905, 898,
       613, 392, 975, 329,  59,  95, 300, 146, 913, 741, 609, 360, 742,
       923, 933, 433, 902, 501, 961, 998, 529, 904, 993, 343, 463, 535,
       579, 334, 823, 231, 762, 645, 175, 309, 571, 339, 639, 456, 432,
       482,  75, 995, 170, 476,  27, 766, 925, 361, 494, 158,  84, 331,
       573, 519, 910, 638, 512, 400, 517, 108, 810, 344, 373, 532, 642,
       222, 879, 530, 572, 616, 214, 718, 675, 621, 829, 849, 636, 412,
       224, 388, 401, 257, 447, 491, 134, 977, 821, 598, 640, 385, 380,
       696,  20, 183, 928, 681, 256, 391,  65, 935,  17,  25, 569, 417,
       279, 406, 498, 631, 199,  72, 405, 543, 507, 804, 565, 697, 815,
       894, 818, 233, 632, 708, 551, 350,   4, 429, 310, 622,  49, 163,
       239, 453, 510, 312,  16, 801, 338, 534, 990,  19,  48, 407, 460,
       137, 511, 455, 906, 152, 500, 109,  36, 885, 670, 210, 775, 764,
       181, 148, 341, 228, 287,  99, 954, 866, 495, 673, 457, 268, 522,
        34, 292, 397, 819, 240, 605, 620, 582, 956, 288, 220, 976, 680,
       834, 779, 427, 196, 771, 784, 665, 599,  45, 319, 960, 759, 301,
       726, 880, 803,  24, 513, 438, 744, 757, 409, 692, 477, 808, 945,
       747, 901, 553,   3, 811, 627, 828, 724, 277, 172, 118, 439, 756,
       891, 267, 825, 164,  51,  92, 702, 472, 856,  90, 711, 842, 370,
       812, 564, 641, 845, 581,  53, 780, 129, 263, 528,  60,  26, 376,
       276, 458, 194, 830, 251, 332, 280, 410,  80, 219, 324, 618,  91,
       470,  43, 441, 120, 890, 701, 123,  81, 218, 442, 249, 552, 858,
       285, 719, 559, 133, 919, 978, 349, 644, 774, 770, 326, 972,   6,
       315, 369, 363, 428, 459, 698,  70, 100, 595,  29, 912, 488, 248,
       624, 682,  82, 991, 862, 155, 986, 850, 889,  74, 144, 226, 217,
       198, 504, 699, 102, 587, 247, 227, 567, 729,  87, 192, 353,  78,
       685, 105, 283, 508, 424, 753, 656, 873, 917, 604, 154, 419, 970,
       533, 602, 846, 791, 191,   2, 187, 445, 577, 813, 416, 694, 269,
       368, 113,   0, 317, 208, 874, 261, 794, 964, 827, 651, 944, 374,
       575, 861, 872, 886, 304, 537, 165, 751, 193, 351, 124, 767, 942,
       110, 867, 563, 347, 795, 568, 943, 768, 704, 379, 957, 755, 545,
       540, 281, 746, 953, 893, 950, 606, 150, 115, 769, 853, 386, 443,
        54, 798, 997, 634, 197, 554, 720, 377, 824, 678, 295, 966,  55,
       265,  71, 949, 478, 173, 211, 167, 870, 864, 969, 225, 266, 714,
       786, 362, 653, 322, 971, 246, 492,  40, 223, 502, 480, 999, 863,
        85, 212, 254, 839, 965, 538, 617,  33, 302, 243, 352,  38, 895,
       608, 918, 987, 524, 875, 831,  96, 340,  67, 252, 585, 393, 418,
       570, 262, 296, 614, 671, 245, 365, 974, 600, 182, 161, 106, 130,
       383, 937, 951, 469,  37, 184, 258,  23, 160,   8, 914, 174, 384,
       371,  94, 884, 314, 132, 930, 773, 221, 364, 754, 320, 852, 318,
       625, 242, 298, 103, 127, 908, 674, 782, 717, 922, 980, 911, 657,
       940, 520, 325, 787, 952, 356, 860, 687, 126, 603, 272, 725, 610,
       337, 176, 497, 776,  15,  61, 941, 486, 916,  56, 518, 237, 316,
       308,  83, 633, 721, 695, 736, 422, 733, 411, 180, 556, 730, 487,
       799, 114, 171, 462, 306, 973, 590, 883,  31, 481,  57, 467, 156,
        47, 274,  73, 594,  79, 431,  21, 710, 546, 628, 503, 601,  30,
       311, 107, 838, 202, 260, 826, 275, 116, 667, 293, 423, 841, 793,
       722, 580, 527, 672, 284, 168, 232, 323, 136, 434, 506,  98, 783,
       871,  44, 909, 179, 435, 649, 562, 238, 664, 395, 921, 709, 938,
       440, 931, 402, 264, 273, 354, 723, 303, 924, 473,  50, 294, 142,
       750, 270, 185, 282, 693, 619, 623, 963, 926, 777, 230, 955, 807,
       122, 297, 643, 588, 650, 112, 888,  62, 141, 984,  64, 313,  41,
        32, 647, 920, 216, 525,  12, 958, 413, 820, 743, 188, 544, 346,
        18, 658, 835, 166, 390,  89, 444, 290, 359, 716, 626, 652, 178,
       576,  10, 857, 706, 615, 760, 752, 851,  28, 162, 688, 104, 420,
         9,  52, 988, 985, 466, 734, 241, 468, 548, 837, 372, 740])

In [36]:
# create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,168.67,557
1,female,group C,some college,standard,completed,69,90,88,188.33,882
2,female,group B,master's degree,standard,none,90,95,93,216.00,555
3,male,group A,associate's degree,free/reduced,none,47,57,44,118.67,558
4,male,group C,some college,standard,none,76,78,75,179.00,336
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,218.67,468
996,male,group C,high school,free/reduced,none,62,55,55,135.33,548
997,female,group C,high school,free/reduced,completed,59,71,65,151.67,837
998,female,group D,some college,standard,completed,68,78,77,171.67,372
999,female,group D,some college,free/reduced,none,77,86,86,191.67,740

In [37]:
# set new_index as the new index for the dataframe
df_exams.set_index('new_index')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
new_index,,,,,,,,,
557,female,group B,bachelor's degree,standard,none,72,72,74,168.67
882,female,group C,some college,standard,completed,69,90,88,188.33
555,female,group B,master's degree,standard,none,90,95,93,216.00
558,male,group A,associate's degree,free/reduced,none,47,57,44,118.67
336,male,group C,some college,standard,none,76,78,75,179.00
...,...,...,...,...,...,...,...,...,...
468,female,group E,master's degree,standard,completed,88,99,95,218.67
548,male,group C,high school,free/reduced,none,62,55,55,135.33
837,female,group C,high school,free/reduced,completed,59,71,65,151.67
372,female,group D,some college,standard,completed,68,78,77,171.67
740,female,group D,some college,free/reduced,none,77,86,86,191.67

In [39]:
df_exams.set_index('new_index', inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
new_index,,,,,,,,,
557,female,group B,bachelor's degree,standard,none,72,72,74,168.67
882,female,group C,some college,standard,completed,69,90,88,188.33
555,female,group B,master's degree,standard,none,90,95,93,216.00
558,male,group A,associate's degree,free/reduced,none,47,57,44,118.67
336,male,group C,some college,standard,none,76,78,75,179.00
...,...,...,...,...,...,...,...,...,...
468,female,group E,master's degree,standard,completed,88,99,95,218.67
548,male,group C,high school,free/reduced,none,62,55,55,135.33
837,female,group C,high school,free/reduced,completed,59,71,65,151.67
372,female,group D,some college,standard,completed,68,78,77,171.67
740,female,group D,some college,free/reduced,none,77,86,86,191.67

In [40]:
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
new_index,,,,,,,,,
0,female,group D,associate's degree,standard,none,76,74,73,174.33
1,female,group B,some high school,free/reduced,none,18,32,28,59.33
2,female,group C,some high school,standard,completed,44,51,55,113.33
3,female,group D,some college,free/reduced,completed,59,78,76,162.33
4,female,group D,master's degree,standard,completed,70,71,74,165.67
...,...,...,...,...,...,...,...,...,...
995,male,group A,some college,free/reduced,none,28,23,19,57.33
996,male,group D,high school,standard,none,76,73,68,171.67
997,female,group E,associate's degree,free/reduced,none,73,76,78,175.00
998,male,group A,some college,standard,none,69,67,69,159.00
999,female,group E,associate's degree,standard,completed,65,75,77,165.67